// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package flatbuffers

import "strconv"

type AccessType int8

const (
	AccessTypeI AccessType = 0
	AccessTypeR AccessType = 1
	AccessTypeW AccessType = 2
)

var EnumNamesAccessType = map[AccessType]string{
	AccessTypeI: "I",
	AccessTypeR: "R",
	AccessTypeW: "W",
}

var EnumValuesAccessType = map[string]AccessType{
	"I": AccessTypeI,
	"R": AccessTypeR,
	"W": AccessTypeW,
}

func (v AccessType) String() string {
	if s, ok := EnumNamesAccessType[v]; ok {
		return s
	}
	return "AccessType(" + strconv.FormatInt(int64(v), 10) + ")"
}
